/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.tutorial.calculadora.view;

import br.com.tutorial.calculadora.model.CalculadoraModel;
import java.util.HashSet;

/**
 *
 * @author night
 */
public class CalculadoraView extends javax.swing.JFrame {

    CalculadoraModel calculadora = new CalculadoraModel();
    boolean segundo = false;
    String operacao;

    /**
     * Creates new form CalculadoraView
     */
    public CalculadoraView() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelVisor = new javax.swing.JLabel();
        jButton1Clear = new javax.swing.JButton();
        jButtonDivi = new javax.swing.JButton();
        jButton1Porcentagem = new javax.swing.JButton();
        jButton1Multiplicaçao = new javax.swing.JButton();
        jButton1Soma = new javax.swing.JButton();
        jButton1Igual = new javax.swing.JButton();
        jButton1Subtraçao = new javax.swing.JButton();
        jButton1Apagar1 = new javax.swing.JButton();
        jButton1Ponto = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelVisor.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        jLabelVisor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabelVisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 6, 360, 110));

        jButton1Clear.setContentAreaFilled(false);
        jButton1Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ClearActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 70, 70));

        jButtonDivi.setContentAreaFilled(false);
        jButtonDivi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiviActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDivi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 70, 70));

        jButton1Porcentagem.setContentAreaFilled(false);
        jButton1Porcentagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1Porcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1PorcentagemActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Porcentagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 70, 80));

        jButton1Multiplicaçao.setContentAreaFilled(false);
        jButton1Multiplicaçao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1Multiplicaçao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1MultiplicaçaoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Multiplicaçao, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 70, 80));

        jButton1Soma.setContentAreaFilled(false);
        jButton1Soma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1Soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SomaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Soma, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 70, 80));

        jButton1Igual.setContentAreaFilled(false);
        jButton1Igual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1IgualActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 70, 160));

        jButton1Subtraçao.setContentAreaFilled(false);
        jButton1Subtraçao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1Subtraçao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SubtraçaoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Subtraçao, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 70, 80));

        jButton1Apagar1.setContentAreaFilled(false);
        jButton1Apagar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1Apagar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1Apagar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Apagar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 70, 70));

        jButton1Ponto.setContentAreaFilled(false);
        jButton1Ponto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1Ponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1PontoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Ponto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 70, 70));

        jButton0.setContentAreaFilled(false);
        jButton0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 70, 70));

        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 70, 70));

        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 70, 70));

        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 70, 70));

        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 70, 70));

        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 70, 70));

        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 70, 70));

        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 70, 70));

        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 70, 70));

        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 70, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/C_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 480, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ClearActionPerformed
        calculadora.setValor1(Double.parseDouble(jLabelVisor.getText()));
        segundo = true;
        jLabelVisor.setText("");
        operacao = "div";
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ClearActionPerformed

    private void jButton1PorcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1PorcentagemActionPerformed
        calculadora.setValor1(Double.parseDouble(jLabelVisor.getText()));
        calculadora.setResultado(calculadora.getValor1() / 100);
        jLabelVisor.setText(String.valueOf(calculadora.getResultado())); // TODO add your handling code here
    }//GEN-LAST:event_jButton1PorcentagemActionPerformed

    private void jButton1MultiplicaçaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1MultiplicaçaoActionPerformed
        calculadora.setValor1(Double.parseDouble(jLabelVisor.getText()));
        segundo = true;
        jLabelVisor.setText("");
        operacao = "multiplicacao";
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MultiplicaçaoActionPerformed

    private void jButton1SomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SomaActionPerformed
        calculadora.setValor1(Double.parseDouble(jLabelVisor.getText()));
        segundo = true;
        jLabelVisor.setText("");
        operacao = "soma";

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1SomaActionPerformed

    private void jButton1IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1IgualActionPerformed
        if (segundo == true) {
            calculadora.setValor2(Double.parseDouble(jLabelVisor.getText()));
            if (operacao == "soma") {
                calculadora.somar();
                jLabelVisor.setText(String.valueOf(calculadora.getResultado()));
                operacao = "";
            }
            if (operacao == "multiplicacao") {
                calculadora.multiplicacao();
                jLabelVisor.setText(String.valueOf(calculadora.getResultado()));
                operacao = "";
            }
            if (operacao == "div") {
                calculadora.div();
                jLabelVisor.setText(String.valueOf(calculadora.getResultado()));
                operacao = "";
            }
            if (operacao == "subtracao") {
                calculadora.subtracao();
                jLabelVisor.setText(String.valueOf(calculadora.getResultado()));
                operacao = "";
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1IgualActionPerformed

    private void jButton1SubtraçaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SubtraçaoActionPerformed
        calculadora.setValor1(Double.parseDouble(jLabelVisor.getText()));
        segundo = true;
        jLabelVisor.setText("");
        operacao = "subtracao";
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1SubtraçaoActionPerformed

    private void jButton1PontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1PontoActionPerformed
        jLabelVisor.setText(jLabelVisor.getText() + (".")); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1PontoActionPerformed

    private void jButton1Apagar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1Apagar1ActionPerformed
        jLabelVisor.setText(jLabelVisor.getText() + ("9"));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1Apagar1ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        jLabelVisor.setText(jLabelVisor.getText() + ("0"));// TODO add your handling code here:
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabelVisor.setText(jLabelVisor.getText() + ("1"));    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLabelVisor.setText(jLabelVisor.getText() + ("2"));     // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jLabelVisor.setText(jLabelVisor.getText() + ("3"));    // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jLabelVisor.setText(jLabelVisor.getText() + ("4"));  // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jLabelVisor.setText(jLabelVisor.getText() + ("5"));    // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jLabelVisor.setText(jLabelVisor.getText() + ("6"));    // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jLabelVisor.setText(jLabelVisor.getText() + ("7"));  // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jLabelVisor.setText(jLabelVisor.getText() + ("8"));     // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
jLabelVisor.setText(jLabelVisor.getText().substring(0, jLabelVisor.getText().length()-1));       // TODO addcalculadora.setValor1(Double.parseDouble(jLabelVisor.getText()));


    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiviActionPerformed
        calculadora.setValor1(0);
        calculadora.setValor2(0);
        segundo = false;
        jLabelVisor.setText("");
        operacao = "";        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDiviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1Apagar1;
    private javax.swing.JButton jButton1Clear;
    private javax.swing.JButton jButton1Igual;
    private javax.swing.JButton jButton1Multiplicaçao;
    private javax.swing.JButton jButton1Ponto;
    private javax.swing.JButton jButton1Porcentagem;
    private javax.swing.JButton jButton1Soma;
    private javax.swing.JButton jButton1Subtraçao;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonDivi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelVisor;
    // End of variables declaration//GEN-END:variables
}
